image: "registry.access.redhat.com/ubi8/python-36"

varaibles:
  PIPENV_VERBOSITY: "-1"

before_script:
- pip install pipenv

styleCheck:
  stage: style_check
  script: 
    - pipenv update --dev
    - pipenv run flake8 --max-line-length 100 osia
    - pipenv run pylint osia

