# This is a basic workflow to help you get started with Actions

name: publish-docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.4
    - name: Publish documentation
      run: |
        git clone https://github.com/mijaros/osia-1 --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
